# Generated by Django 5.2.7 on 2025-10-08 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MusicPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("composer", models.CharField(blank=True, max_length=100)),
                (
                    "sheet_music",
                    models.FileField(blank=True, null=True, upload_to="sheet_music/"),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part", models.CharField(blank=True, max_length=50)),
                ("recording_file", models.FileField(upload_to="recordings/")),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "music_piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="music.musicpiece",
                    ),
                ),
            ],
        ),
    ]
