# Generated by Django 5.2.7 on 2025-10-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="recording_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
