# Generated by Django 5.2.7 on 2025-10-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='musicpiece',
            unique_together={('title', 'composer')},
        ),
    ]
