# Generated by Django 5.2.7 on 2025-10-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_musicpiece_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('music_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='music.musicpiece')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
