# Generated by Django 5.2.7 on 2025-10-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_recording_recording_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recording",
            name="recording_file",
            field=models.FileField(blank=True, null=True, upload_to="recordings/"),
        ),
    ]
