# Generated by Django 5.2.7 on 2025-10-16 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='music.movement'),
        ),
    ]
